[project]
name = "pulse-backend"
version = "0.1.0"
dependencies = [
    "litestar[pydantic,jwt,sqlalchemy,standard]",
    "asyncpg",
    "bcrypt",
]

[project.optional-dependencies]
lint = ["ruff", "mypy"]

[tool.pip-tools]
generate-hashes = true

[tool.ruff]
line-length = 79
target-version = "py312"

[tool.ruff.lint]
select = [
    "F",  # Pyflakes
    "E",  # pycodestyle
    "W",  # pycodestyle
    "C90",  # mccabe
    "I",  # isort
    "UP",  # pyupgrade
    "S",  # flake8-bandit
    "RUF",  # RUF
]

[tool.mypy]
python_version = "3.12"
strict = true
