[project]
name = "pulse-backend"
version = "0.1.0"
dependencies = [
    "litestar[pydantic,jwt,sqlalchemy,standard]",
    "asyncpg",
]

[tool.pip-tools]
generate-hashes = true

[tool.ruff]
line-length = 79
target-version = "py312"

[tool.ruff.lint]
select = ["F", "E", "W", "C90", "I", "N"]

[tool.mypy]
python_version = "3.12"
strict = true
